Add openssl1.1.1o to recipes-connectivity
As the priority of this layer is higher than openembedded-core, this
gets pulled in rather than openssl1.1.1l, which has a rather unfortunate
bug in it (which got patched up later in openembedded-core with build target
reproducibility). This showed up as a rather strange problem with mbed-fcce,
where the build failed with a Python error similar to this:

|  File "/build/build-lmp/tmp-lmp/work/cortexa53-lmp-linux/mbed-fcce/4.11.1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
|    import OpenSSL.SSL
|  File "/build/build-lmp/tmp-lmp/work/cortexa53-lmp-linux/mbed-fcce/4.11.1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
|    from OpenSSL import crypto, SSL
|  File "/build/build-lmp/tmp-lmp/work/cortexa53-lmp-linux/mbed-fcce/4.11.1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1556, in <module>
|    class X509StoreFlags(object):
|  File "/build/build-lmp/tmp-lmp/work/cortexa53-lmp-linux/mbed-fcce/4.11.1-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
|    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
| AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
| WARNING: exit code 1 from a shell command.

For info on the patch (later then migrated into the openssl itself).

https://source.foundries.io/lmp-mirrors/openembedded-core.git/tree/meta/recipes-connectivity/openssl/openssl/reproducible.patch?h=hardknott