This fix the FCCE compilation with/without PARSEC_TPM_SE_SUPPORT enabled (#277)
When compiling without parsec, build results into failure -

```
error: redefinition of 'struct itimerspec'
```

The git patches are only required when compiling with PARSEC_TPM_SE_SUPPORT flag